"use client";

export {
  PromptInputProvider,
  usePromptInputController,
  useProviderAttachments,
  type AttachmentsContext,
  type PromptInputControllerProps,
  type PromptInputProviderProps,
  type TextInputContext,
} from "./prompt-input-context";
export {
  PromptInputAttachment,
  PromptInputAttachments,
  PromptInputActionAddAttachments,
  usePromptInputAttachments,
  type PromptInputActionAddAttachmentsProps,
  type PromptInputAttachmentProps,
  type PromptInputAttachmentsProps,
} from "./prompt-input-attachments";
export {
  PromptInput,
  PromptInputBody,
  PromptInputButton,
  PromptInputFooter,
  PromptInputHeader,
  PromptInputSubmit,
  PromptInputTextarea,
  PromptInputTools,
  type PromptInputBodyProps,
  type PromptInputButtonProps,
  type PromptInputFooterProps,
  type PromptInputHeaderProps,
  type PromptInputMessage,
  type PromptInputProps,
  type PromptInputSubmitProps,
  type PromptInputTextareaProps,
  type PromptInputToolsProps,
} from "./prompt-input-shell";
export {
  PromptInputSpeechButton,
  type PromptInputSpeechButtonProps,
} from "./prompt-input-speech";
export {
  PromptInputActionMenu,
  PromptInputActionMenuContent,
  PromptInputActionMenuItem,
  PromptInputActionMenuTrigger,
  PromptInputCommand,
  PromptInputCommandEmpty,
  PromptInputCommandGroup,
  PromptInputCommandInput,
  PromptInputCommandItem,
  PromptInputCommandList,
  PromptInputCommandSeparator,
  PromptInputHoverCard,
  PromptInputHoverCardContent,
  PromptInputHoverCardTrigger,
  PromptInputSelect,
  PromptInputSelectContent,
  PromptInputSelectItem,
  PromptInputSelectTrigger,
  PromptInputSelectValue,
  PromptInputTab,
  PromptInputTabBody,
  PromptInputTabItem,
  PromptInputTabLabel,
  PromptInputTabsList,
  type PromptInputActionMenuContentProps,
  type PromptInputActionMenuItemProps,
  type PromptInputActionMenuProps,
  type PromptInputActionMenuTriggerProps,
  type PromptInputCommandEmptyProps,
  type PromptInputCommandGroupProps,
  type PromptInputCommandInputProps,
  type PromptInputCommandItemProps,
  type PromptInputCommandListProps,
  type PromptInputCommandProps,
  type PromptInputCommandSeparatorProps,
  type PromptInputHoverCardContentProps,
  type PromptInputHoverCardProps,
  type PromptInputHoverCardTriggerProps,
  type PromptInputSelectContentProps,
  type PromptInputSelectItemProps,
  type PromptInputSelectProps,
  type PromptInputSelectTriggerProps,
  type PromptInputSelectValueProps,
  type PromptInputTabBodyProps,
  type PromptInputTabItemProps,
  type PromptInputTabLabelProps,
  type PromptInputTabProps,
  type PromptInputTabsListProps,
} from "./prompt-input-primitives";
