/**
 * CSRF Protection Middleware
 *
 * Implements Double Submit Cookie pattern for CSRF protection.
 * - Generates CSRF tokens for safe HTTP methods (GET, HEAD, OPTIONS)
 * - Validates CSRF tokens for unsafe methods (POST, PUT, DELETE, PATCH)
 * - Sets httpOnly cookie with CSRF token
 * - Returns token in X-CSRF-Token response header
 *
 * Security:
 * - Tokens are cryptographically random (crypto.randomBytes)
 * - Validation uses HMAC to prevent forgery
 * - Cookies are httpOnly to prevent XSS
 * - Cookies use sameSite to prevent cross-site attacks
 */

import type { Request, Response, NextFunction } from "express";
import { validateCsrfToken } from "../lib/csrf.js";
import { AppError, ERROR_CODES, HTTP_STATUS } from "../lib/errors/index.js";
import logger from "../lib/logger.js";

// Cookie name for CSRF token
const CSRF_COOKIE_NAME = "csrf_token";

// Header name for CSRF token
const CSRF_HEADER_NAME = "x-csrf-token";

// Safe HTTP methods that don't require CSRF protection
const SAFE_METHODS = new Set(["GET", "HEAD", "OPTIONS"]);

/**
 * CSRF Token Validation Error (403)
 * Thrown when CSRF token is missing or invalid
 */
class CsrfError extends AppError {
  constructor(message = "CSRF token validation failed") {
    super(message, ERROR_CODES.FORBIDDEN, HTTP_STATUS.FORBIDDEN, true);
  }
}

/**
 * Get CSRF token from request cookie
 */
function getTokenFromCookie(req: Request): string | null {
  return req.cookies?.[CSRF_COOKIE_NAME] || null;
}

/**
 * Get CSRF token from request header
 */
function getTokenFromHeader(req: Request): string | null {
  const header = req.headers[CSRF_HEADER_NAME];
  if (typeof header === "string") {
    return header;
  }
  if (Array.isArray(header)) {
    return header[0] || null;
  }
  return null;
}

/**
 * Determine if request requires CSRF protection
 */
function requiresCsrfProtection(req: Request): boolean {
  // Safe methods don't require CSRF protection
  if (SAFE_METHODS.has(req.method)) {
    return false;
  }

  // All state-changing methods require CSRF protection
  return true;
}

interface ConnectionWithRemoteAddress {
  remoteAddress?: string;
}

/**
 * Log CSRF validation failure
 */
function logCsrfFailure(req: Request, reason: string): void {
  const connection = req.connection as ConnectionWithRemoteAddress | undefined;
  logger.warn(
    {
      requestId: req.id,
      method: req.method,
      url: req.url,
      userId: req.authUserId || req.internalAuth?.userId,
      organizationId: req.authOrgId || req.internalAuth?.orgId || null,
      ip: req.ip || req.headers["x-forwarded-for"] || connection?.remoteAddress,
      reason,
    },
    `CSRF validation failed: ${reason}`
  );
}

/**
 * CSRF Protection Middleware
 *
 * For safe methods (GET, HEAD, OPTIONS):
 * - Generates a new CSRF token if one doesn't exist
 * - Sets the token in a cookie
 * - Includes the token in X-CSRF-Token response header
 *
 * For unsafe methods (POST, PUT, DELETE, PATCH):
 * - Validates that the CSRF token from header matches cookie
 * - Throws CsrfError (403) if validation fails
 */
export function csrfProtection(req: Request, res: Response, next: NextFunction): void {
  try {
    // For safe methods, pass through existing token (no generation).
    // New tokens are ONLY generated by the /api/csrf-token endpoint
    // to prevent race conditions with parallel GET requests.
    if (!requiresCsrfProtection(req)) {
      const token = getTokenFromCookie(req);
      if (token) {
        req.csrfToken = token;
      }
      next();
      return;
    }

    // For unsafe methods, validate token
    const cookieToken = getTokenFromCookie(req);
    const headerToken = getTokenFromHeader(req);

    // Check if tokens are present
    if (!cookieToken) {
      logCsrfFailure(req, "Missing CSRF cookie");
      throw new CsrfError("CSRF token missing from cookie");
    }

    if (!headerToken) {
      logCsrfFailure(req, "Missing CSRF header");
      throw new CsrfError("CSRF token missing from request header");
    }

    // Validate that header token matches cookie token
    if (cookieToken !== headerToken) {
      logCsrfFailure(req, "CSRF token mismatch");
      throw new CsrfError("CSRF token mismatch");
    }

    // Validate token signature
    if (!validateCsrfToken(cookieToken)) {
      logCsrfFailure(req, "Invalid CSRF token signature");
      throw new CsrfError("Invalid CSRF token");
    }

    // Token is valid, store on request and continue
    req.csrfToken = cookieToken;

    next();
  } catch (error) {
    // Pass error to error handler middleware
    next(error);
  }
}

/**
 * Middleware to skip CSRF protection for specific routes
 * Use this for routes that don't need CSRF protection (e.g., webhooks)
 */
export function skipCsrfProtection(req: Request, _res: Response, next: NextFunction): void {
  req.skipCsrfProtection = true;
  next();
}

/**
 * Conditional CSRF protection wrapper
 * Skips CSRF if req.skipCsrfProtection is set
 */
export function conditionalCsrfProtection(req: Request, res: Response, next: NextFunction): void {
  if (req.skipCsrfProtection) {
    next();
    return;
  }
  csrfProtection(req, res, next);
}
