/**
 * CSRF Token Generation and Validation
 *
 * Provides cryptographically secure CSRF protection using the Double Submit Cookie pattern.
 * - Tokens are generated using crypto.randomBytes for cryptographic randomness
 * - Validation uses HMAC to prevent token forgery
 * - Minimum token length of 32 bytes for security
 *
 * Security guarantees:
 * - Tokens cannot be guessed (cryptographically random)
 * - Tokens cannot be forged (HMAC signed with secret)
 * - Timing-safe comparison prevents timing attacks
 */

import crypto from 'crypto';

function resolveCsrfSecret(): string {
  const envSecret = process.env.CSRF_SECRET?.trim();
  if (envSecret) {
    return envSecret;
  }

  throw new Error(
    'CSRF_SECRET environment variable must be set. ' +
    'Generate one with: node -e "console.log(require(\'crypto\').randomBytes(64).toString(\'hex\'))"'
  );
}

// CSRF secret key for HMAC signing
const CSRF_SECRET = resolveCsrfSecret();

// Token length in bytes (32 bytes = 256 bits)
const TOKEN_LENGTH = 32;

/**
 * Generate a cryptographically secure CSRF token
 *
 * Creates a random token and signs it with HMAC to prevent forgery.
 * The token is a combination of random bytes and an HMAC signature.
 *
 * @returns Base64-encoded CSRF token
 */
export function generateCsrfToken(): string {
  // Generate cryptographically secure random bytes
  const randomBytes = crypto.randomBytes(TOKEN_LENGTH);

  // Create HMAC signature of the random bytes
  const hmac = crypto.createHmac('sha256', CSRF_SECRET);
  hmac.update(randomBytes);
  const signature = hmac.digest('base64');

  // Combine random bytes and signature
  const tokenValue = randomBytes.toString('base64');
  const token = `${tokenValue}|${signature}`;

  return token;
}

/**
 * Validate a CSRF token
 *
 * Verifies that the token was generated by our system and hasn't been tampered with.
 * Uses timing-safe comparison to prevent timing attacks.
 *
 * @param token - The CSRF token to validate
 * @returns True if token is valid, false otherwise
 */
export function validateCsrfToken(token: string | undefined | null): boolean {
  if (!token || typeof token !== 'string') {
    return false;
  }

  // Split token into value and signature
  const parts = token.split('|');
  if (parts.length !== 2) {
    return false;
  }

  const [tokenValue, providedSignature] = parts;

  try {
    // Recreate HMAC signature from token value
    const randomBytes = Buffer.from(tokenValue!, 'base64');
    const hmac = crypto.createHmac('sha256', CSRF_SECRET);
    hmac.update(randomBytes);
    const expectedSignature = hmac.digest('base64');

    // Use timing-safe comparison to prevent timing attacks
    return crypto.timingSafeEqual(
      Buffer.from(providedSignature!),
      Buffer.from(expectedSignature)
    );
  } catch {
    // Invalid base64 or buffer comparison failed
    return false;
  }
}

/**
 * Get the CSRF secret (for testing/debugging purposes only)
 * @private
 */
export function _getCsrfSecret(): string {
  return CSRF_SECRET;
}
